version: "3"

services:
  frontend:
    container_name: front-end
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    depends_on:
      - backend

  backend:
    container_name: back-end
    build:
      context: ./backend/
      dockerfile: Dockerfile