name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: '389.0.0'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker authentication with GCP
      run: |
        echo ${GCP_SA_KEY} | gcloud auth activate-service-account --key-file=-
        gcloud auth configure-docker asia.gcr.io
        if [ $? -eq 0 ]; then
          echo "Docker authentication with GCP successful"
        else
          echo "Docker authentication with GCP failed" >&2
          exit 1
        fi

    - name: Build and push Docker image
      run: |
        docker build -t asia.gcr.io/justtuananh/backend:$GITHUB_SHA .
        docker push asia.gcr.io/justtuananh/backend:$GITHUB_SHA

    - name: Deploy to GKE
      run: |
        kubectl apply -f backend-deployment.yaml
