name: CI/CD Deployment to GKE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          sudo apt-get update && sudo apt-get install -y docker.io

      - name: Build Docker image
        run: |
          docker build -t asia.gcr.io/justtuananh/backend:v1 .

      - name: Authenticate to Cloud Build
        uses: google-cloud/cloud-build-action@v2
        with:
          serviceAccountFile: ${{ secrets.GCP_SA_KEY }}

      - name: Push Docker image to Cloud Build
        uses: docker/push-action@v3
        with:
          repository: asia.gcr.io/justtuananh/backend
          tag: v1

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up kubectl
        run: |
          sudo apt-get update && sudo apt-get install -y kubectl

      - name: Authenticate to GKE
        uses: GoogleCloudPlatform/gke-auth-action@v2
        with:
          cloud_project_id: justtuananh
          cluster_name: autopilot-cluster-1   
          service_account_file: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy application
        run: |
          kubectl apply -f backend-deployment.yaml
