# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: autopilot-cluster-1    
  GKE_ZONE: us-central1  
  DEPLOYMENT_NAME: gke-test
  IMAGE: backend

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
      with:
        service_account_key: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAianVzdHR1YW5h bmgiLAogICJwcml2YXRlX2tleV9pZCI6ICIyNzNlOTIyNWZhNTk2OGY3MzllODEwNGYyZjFkZjVk MDMwYWFhYzNiIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t XG5NSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUURNVWhv dU9oWmRuOE5PXG5pcm5DR2tzSHhPeVZFZkZGS0ZlZ3VGVFRKTlVxVW5LRk9rdnI1bktZQ20xWnlC OXA5UDZwNXFaNjdJQjh2azBPXG5OZm5CUXo3bEswZWZYVWx2VkV6dkl2cUZyMHdJd3UvOFg5ZjBB d0VzcnJWL29oSWZheVQ2bVBDWEROZ05OdGtCXG5BRHU0SGt2alZ6SjM2WkJUaGcvdWRmUU91WU50 czFtdE90Rmg1QW5kVHlpMlBMdkNSTlF6RTdETHEyRjdwbUFHXG5mMDF5aEF0UVdudzdKT2txTTNN cW5qL1pLcVd0WXp5OGF1cnJqQzhUc0Z0U3RweUtXS3BBcXhNZVZ5U2diSnJUXG5vN3I5ZER4MEk3 ckJsL1BhUHQ0RkJLRXVJUEdBZHg2SmZiMG5rS1NZTjhKcFg4c2ZQYzBISlNJTTFZR1FqTWZBXG55 b3ZSalNINUFnTUJBQUVDZ2dFQVZ4dS92cXFVSTNrNzlvM05VVlFOWGZRV1d4MkpxODdkd1E4bFZ0 bHlxZmI1XG5qUlJFRHdBeUplRDRLdGxYajBCY25FblIrMEUrTERDandHWEJvNlFNT2Y3Z0s3REZZ Sm5qck9aUVFWTnhpcUMxXG5XUGJ4cGozcnI4V1NhcVpKckt4czJRd0FNcDNPdEorSUY5V21JRUtH WHhlclZCVTNLMnpSK1B1L3Y5RldsNXNtXG5scVhncWlJYmpPOEhTNzNncWplYXJUY2tIR3UrdkRB bldKc2VqZW14OXorWXdZS2FQZVYxUUNjT3NYem9kSDM4XG5GeWt3Q21DRk16NEFkamlQOTNaMnZt MEkxYjFoSmRTd3UydU5WMGJFdEtXK2RYUnd4dEpRRUduSUtNQU5TakNSXG5VTkh1ZUVzNUsrMlNP YndmQXFpdWNod1ZBcWRsbHdtbUErRXVVbnUrd3dLQmdRRHAxWlNhYldOOEVXTXlXMm5qXG5mOXFa d01RMjZuaTJFQlgwcXJ2UkhESG1yQUQyRXM4ZW1CUWVWb2dSN2V5dWtyMnhFMWZXWExOeXRxd1FI VjNUXG40R3JsUFp1cFRkMVBZcXhQZUxFSzVZVlNRcDBHWTFNWGlkT1ppVWJubnZpeGJ3SFcwZDBR OXVvbG5KQnliWjNNXG5Ma3JwQmVpRXVNemtIZDFXMjArTTZqRG1Ld0tCZ1FEZnNGSC9DK1ZLd0Rp QWxzTVFRanF2bTFyU0ZiZTdqMnJXXG4rem1lWWxTVTJDaFNnMXdML3BEY1E5VUhDSmpqWERWUGxP eU5CZy9Lb0c1clRVNWErempnT0hKUVRjNHYzU1pPXG5vQTFnRmNVYmR2TVpOMVdvV1B3bkJqL2FK UTBNQlBaR3lLVDJaeCtMWDZtb0ZlZG1HT2RveHl6RFBEZVBnT2N2XG5JakF3SS8zS2F3S0JnRG5F NFZ5eGo3VjBHanl6cHRwa21ONEphTEJraHdQN3YyRGQyVjdWQjJNRXRZd1ZvNFBjXG5jSVA2UHMy bktTVUw3YjlVbHd2SGhUSGUvVzFSdy85M1h4RlpnaDUydFNsS3FHVk4zUGRqTXVmYXV5NTcxV2hv XG5UWldOKzYxM2NkdHNJRmt4S2R0cUZQakwwRWZrMnVvNXVab09NcDZ2aFRjS1JjZVNrUG13VmZw WEFvR0JBSWtVXG5Zb3RyM000Y1VnUHJZQXE4cTM0bU5GZitXeVFqMVpOOVRXZ1VWa1VJMmwwR2h3 Z0tydmRzMGtXSExUcFhyWXZoXG5kYjFPYzZyMitmUGo0aHE3VGJXS29mTTRXeHpWNTczVE01OG9l Q3hHanQ5ckc2RVpOeDBySlVJbjVvRHhJWU5yXG5QanlLSWJpbG5UQ1dpOEh6alF5VzBvV3FoMW4z NHJUdHZKNGowRW1WQW9HQkFKeU9ENmlXNUUzVmw1c3kxeUp5XG5qNWhQa0I1Z3ZudXRzRDlIcDU3 RjlBbG9JR0ZzYXIyZGtUMTVRVllXZ3lHUlp3dDJNTGMwZitjTWtCRWZQVXBvXG5vZjE0ZENqNEZv SURSZlFnblFBQ1RmSmdJRXRCZlM5SVQxK2tLemlWa1VQMVBkcWR0N2FKT1A1WG1sKzB3Qi92XG5q UlNJYk9ZdUlFM0pqbGFRblg2Ri81R1Ncbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAg ImNsaWVudF9lbWFpbCI6ICJjbG91ZC1iZUBqdXN0dHVhbmFuaC5pYW0uZ3NlcnZpY2VhY2NvdW50 LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMDEzMDk5NjY0NTU0NjM1ODkzMDUiLAogICJhdXRoX3Vy aSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2Vu X3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJv dmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIv djEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVh cGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L2Nsb3VkLWJlJTQwanVzdHR1YW5hbmguaWFt LmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5j b20iCn0K
        project_id: justtuananh

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
      with:
        cluster_name: autopilot-cluster-1   
        location: us-central1 
        credentials: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAianVzdHR1YW5h bmgiLAogICJwcml2YXRlX2tleV9pZCI6ICIyNzNlOTIyNWZhNTk2OGY3MzllODEwNGYyZjFkZjVk MDMwYWFhYzNiIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t XG5NSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUURNVWhv dU9oWmRuOE5PXG5pcm5DR2tzSHhPeVZFZkZGS0ZlZ3VGVFRKTlVxVW5LRk9rdnI1bktZQ20xWnlC OXA5UDZwNXFaNjdJQjh2azBPXG5OZm5CUXo3bEswZWZYVWx2VkV6dkl2cUZyMHdJd3UvOFg5ZjBB d0VzcnJWL29oSWZheVQ2bVBDWEROZ05OdGtCXG5BRHU0SGt2alZ6SjM2WkJUaGcvdWRmUU91WU50 czFtdE90Rmg1QW5kVHlpMlBMdkNSTlF6RTdETHEyRjdwbUFHXG5mMDF5aEF0UVdudzdKT2txTTNN cW5qL1pLcVd0WXp5OGF1cnJqQzhUc0Z0U3RweUtXS3BBcXhNZVZ5U2diSnJUXG5vN3I5ZER4MEk3 ckJsL1BhUHQ0RkJLRXVJUEdBZHg2SmZiMG5rS1NZTjhKcFg4c2ZQYzBISlNJTTFZR1FqTWZBXG55 b3ZSalNINUFnTUJBQUVDZ2dFQVZ4dS92cXFVSTNrNzlvM05VVlFOWGZRV1d4MkpxODdkd1E4bFZ0 bHlxZmI1XG5qUlJFRHdBeUplRDRLdGxYajBCY25FblIrMEUrTERDandHWEJvNlFNT2Y3Z0s3REZZ Sm5qck9aUVFWTnhpcUMxXG5XUGJ4cGozcnI4V1NhcVpKckt4czJRd0FNcDNPdEorSUY5V21JRUtH WHhlclZCVTNLMnpSK1B1L3Y5RldsNXNtXG5scVhncWlJYmpPOEhTNzNncWplYXJUY2tIR3UrdkRB bldKc2VqZW14OXorWXdZS2FQZVYxUUNjT3NYem9kSDM4XG5GeWt3Q21DRk16NEFkamlQOTNaMnZt MEkxYjFoSmRTd3UydU5WMGJFdEtXK2RYUnd4dEpRRUduSUtNQU5TakNSXG5VTkh1ZUVzNUsrMlNP YndmQXFpdWNod1ZBcWRsbHdtbUErRXVVbnUrd3dLQmdRRHAxWlNhYldOOEVXTXlXMm5qXG5mOXFa d01RMjZuaTJFQlgwcXJ2UkhESG1yQUQyRXM4ZW1CUWVWb2dSN2V5dWtyMnhFMWZXWExOeXRxd1FI VjNUXG40R3JsUFp1cFRkMVBZcXhQZUxFSzVZVlNRcDBHWTFNWGlkT1ppVWJubnZpeGJ3SFcwZDBR OXVvbG5KQnliWjNNXG5Ma3JwQmVpRXVNemtIZDFXMjArTTZqRG1Ld0tCZ1FEZnNGSC9DK1ZLd0Rp QWxzTVFRanF2bTFyU0ZiZTdqMnJXXG4rem1lWWxTVTJDaFNnMXdML3BEY1E5VUhDSmpqWERWUGxP eU5CZy9Lb0c1clRVNWErempnT0hKUVRjNHYzU1pPXG5vQTFnRmNVYmR2TVpOMVdvV1B3bkJqL2FK UTBNQlBaR3lLVDJaeCtMWDZtb0ZlZG1HT2RveHl6RFBEZVBnT2N2XG5JakF3SS8zS2F3S0JnRG5F NFZ5eGo3VjBHanl6cHRwa21ONEphTEJraHdQN3YyRGQyVjdWQjJNRXRZd1ZvNFBjXG5jSVA2UHMy bktTVUw3YjlVbHd2SGhUSGUvVzFSdy85M1h4RlpnaDUydFNsS3FHVk4zUGRqTXVmYXV5NTcxV2hv XG5UWldOKzYxM2NkdHNJRmt4S2R0cUZQakwwRWZrMnVvNXVab09NcDZ2aFRjS1JjZVNrUG13VmZw WEFvR0JBSWtVXG5Zb3RyM000Y1VnUHJZQXE4cTM0bU5GZitXeVFqMVpOOVRXZ1VWa1VJMmwwR2h3 Z0tydmRzMGtXSExUcFhyWXZoXG5kYjFPYzZyMitmUGo0aHE3VGJXS29mTTRXeHpWNTczVE01OG9l Q3hHanQ5ckc2RVpOeDBySlVJbjVvRHhJWU5yXG5QanlLSWJpbG5UQ1dpOEh6alF5VzBvV3FoMW4z NHJUdHZKNGowRW1WQW9HQkFKeU9ENmlXNUUzVmw1c3kxeUp5XG5qNWhQa0I1Z3ZudXRzRDlIcDU3 RjlBbG9JR0ZzYXIyZGtUMTVRVllXZ3lHUlp3dDJNTGMwZitjTWtCRWZQVXBvXG5vZjE0ZENqNEZv SURSZlFnblFBQ1RmSmdJRXRCZlM5SVQxK2tLemlWa1VQMVBkcWR0N2FKT1A1WG1sKzB3Qi92XG5q UlNJYk9ZdUlFM0pqbGFRblg2Ri81R1Ncbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAg ImNsaWVudF9lbWFpbCI6ICJjbG91ZC1iZUBqdXN0dHVhbmFuaC5pYW0uZ3NlcnZpY2VhY2NvdW50 LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMDEzMDk5NjY0NTU0NjM1ODkzMDUiLAogICJhdXRoX3Vy aSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2Vu X3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJv dmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIv djEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVh cGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L2Nsb3VkLWJlJTQwanVzdHR1YW5hbmguaWFt LmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5j b20iCn0K


    - name: Print env and secrets
      run: |
        echo "PROJECT_ID: ${{ env.PROJECT_ID }}"
        echo "GKE_CLUSTER: ${{ env.GKE_CLUSTER }}"
        echo "GKE_ZONE: ${{ env.GKE_ZONE }}"
        echo "DEPLOYMENT_NAME: ${{ env.DEPLOYMENT_NAME }}"
        echo "IMAGE: ${{ env.IMAGE }}"
        echo "GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}"  # Cẩn thận khi in ra thông tin nhạy cảm


    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "asia.gcr.io/justtuananh/backend:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "asia.gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"

    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        ./kustomize edit set image asia.gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/gke-test
        kubectl get services -o wide
