name: Backend CI/CD

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: autopilot-cluster-1    # Add your cluster name here.
  GKE_ZONE: us-central1   # Add your cluster zone here.
  DEPLOYMENT_NAME: gke-test # Add your deployment name here.
  IMAGE: backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: 'autopilot-cluster-1'
        location: 'us-central1'


    - run: |-
        gcloud container clusters get-credentials autopilot-cluster-1 --region us-central1 --project justtuananh


    - name: Build and push Docker image
      run: |
        docker build -t asia.gcr.io/justtuananh/backend:$GITHUB_SHA .
        docker push asia.gcr.io/justtuananh/backend:$GITHUB_SHA

    - name: Deploy to GKE
      run: |
        kubectl apply -f backend-deployment.yaml
